// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Use environment variables for Supabase configuration
// These are safe to expose on the frontend (anon key is public by design)
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://tamwvwieljcptseazodc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbXd2d2llbGpjcHRzZWF6b2RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4NjAwNzYsImV4cCI6MjA4MDQzNjA3Nn0.vZWed-klRUvskz0JmRunbGd8E4EzHSbcfW4RBGIf4OU";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY"
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
